// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api.proto

package grpcapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Count         uint32                 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemRequest) Reset() {
	*x = ItemRequest{}
	mi := &file_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemRequest) ProtoMessage() {}

func (x *ItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemRequest.ProtoReflect.Descriptor instead.
func (*ItemRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

func (x *ItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ItemRequest) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	ReserveId     string                 `protobuf:"bytes,2,opt,name=reserve_id,json=reserveId,proto3" json:"reserve_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemResponse) Reset() {
	*x = ItemResponse{}
	mi := &file_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemResponse) ProtoMessage() {}

func (x *ItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemResponse.ProtoReflect.Descriptor instead.
func (*ItemResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *ItemResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ItemResponse) GetReserveId() string {
	if x != nil {
		return x.ReserveId
	}
	return ""
}

type CancelReserveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReserveId     string                 `protobuf:"bytes,1,opt,name=reserve_id,json=reserveId,proto3" json:"reserve_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelReserveRequest) Reset() {
	*x = CancelReserveRequest{}
	mi := &file_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelReserveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelReserveRequest) ProtoMessage() {}

func (x *CancelReserveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelReserveRequest.ProtoReflect.Descriptor instead.
func (*CancelReserveRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

func (x *CancelReserveRequest) GetReserveId() string {
	if x != nil {
		return x.ReserveId
	}
	return ""
}

type CancelReserveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelReserveResponse) Reset() {
	*x = CancelReserveResponse{}
	mi := &file_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelReserveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelReserveResponse) ProtoMessage() {}

func (x *CancelReserveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelReserveResponse.ProtoReflect.Descriptor instead.
func (*CancelReserveResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3}
}

func (x *CancelReserveResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type AddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         int32                  `protobuf:"varint,1,opt,name=table,proto3" json:"table,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressRequest) Reset() {
	*x = AddressRequest{}
	mi := &file_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressRequest) ProtoMessage() {}

func (x *AddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressRequest.ProtoReflect.Descriptor instead.
func (*AddressRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{4}
}

func (x *AddressRequest) GetTable() int32 {
	if x != nil {
		return x.Table
	}
	return 0
}

type AddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Added         bool                   `protobuf:"varint,1,opt,name=added,proto3" json:"added,omitempty"`
	MoreInfo      string                 `protobuf:"bytes,2,opt,name=more_info,json=moreInfo,proto3" json:"more_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressResponse) Reset() {
	*x = AddressResponse{}
	mi := &file_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressResponse) ProtoMessage() {}

func (x *AddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressResponse.ProtoReflect.Descriptor instead.
func (*AddressResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{5}
}

func (x *AddressResponse) GetAdded() bool {
	if x != nil {
		return x.Added
	}
	return false
}

func (x *AddressResponse) GetMoreInfo() string {
	if x != nil {
		return x.MoreInfo
	}
	return ""
}

type CancelDeliveryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelDeliveryRequest) Reset() {
	*x = CancelDeliveryRequest{}
	mi := &file_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelDeliveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelDeliveryRequest) ProtoMessage() {}

func (x *CancelDeliveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelDeliveryRequest.ProtoReflect.Descriptor instead.
func (*CancelDeliveryRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{6}
}

func (x *CancelDeliveryRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type CancelDeliveryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelDeliveryResponse) Reset() {
	*x = CancelDeliveryResponse{}
	mi := &file_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelDeliveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelDeliveryResponse) ProtoMessage() {}

func (x *CancelDeliveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelDeliveryResponse.ProtoReflect.Descriptor instead.
func (*CancelDeliveryResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{7}
}

func (x *CancelDeliveryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ConfirmatorInfoRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ConfirmationEmployeeId string                 `protobuf:"bytes,1,opt,name=confirmation_employee_id,json=confirmationEmployeeId,proto3" json:"confirmation_employee_id,omitempty"`
	ConfirmationType       []string               `protobuf:"bytes,2,rep,name=confirmation_type,json=confirmationType,proto3" json:"confirmation_type,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ConfirmatorInfoRequest) Reset() {
	*x = ConfirmatorInfoRequest{}
	mi := &file_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmatorInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmatorInfoRequest) ProtoMessage() {}

func (x *ConfirmatorInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmatorInfoRequest.ProtoReflect.Descriptor instead.
func (*ConfirmatorInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{8}
}

func (x *ConfirmatorInfoRequest) GetConfirmationEmployeeId() string {
	if x != nil {
		return x.ConfirmationEmployeeId
	}
	return ""
}

func (x *ConfirmatorInfoRequest) GetConfirmationType() []string {
	if x != nil {
		return x.ConfirmationType
	}
	return nil
}

type ConfirmatorInfoResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Sent           bool                   `protobuf:"varint,1,opt,name=sent,proto3" json:"sent,omitempty"`
	ConfirmationId string                 `protobuf:"bytes,2,opt,name=confirmation_id,json=confirmationId,proto3" json:"confirmation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConfirmatorInfoResponse) Reset() {
	*x = ConfirmatorInfoResponse{}
	mi := &file_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmatorInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmatorInfoResponse) ProtoMessage() {}

func (x *ConfirmatorInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmatorInfoResponse.ProtoReflect.Descriptor instead.
func (*ConfirmatorInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{9}
}

func (x *ConfirmatorInfoResponse) GetSent() bool {
	if x != nil {
		return x.Sent
	}
	return false
}

func (x *ConfirmatorInfoResponse) GetConfirmationId() string {
	if x != nil {
		return x.ConfirmationId
	}
	return ""
}

type CancelConfirmationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConfirmationId string                 `protobuf:"bytes,1,opt,name=confirmation_id,json=confirmationId,proto3" json:"confirmation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CancelConfirmationRequest) Reset() {
	*x = CancelConfirmationRequest{}
	mi := &file_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelConfirmationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelConfirmationRequest) ProtoMessage() {}

func (x *CancelConfirmationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelConfirmationRequest.ProtoReflect.Descriptor instead.
func (*CancelConfirmationRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{10}
}

func (x *CancelConfirmationRequest) GetConfirmationId() string {
	if x != nil {
		return x.ConfirmationId
	}
	return ""
}

type CancelConfirmationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelConfirmationResponse) Reset() {
	*x = CancelConfirmationResponse{}
	mi := &file_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelConfirmationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelConfirmationResponse) ProtoMessage() {}

func (x *CancelConfirmationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelConfirmationResponse.ProtoReflect.Descriptor instead.
func (*CancelConfirmationResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{11}
}

func (x *CancelConfirmationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_proto protoreflect.FileDescriptor

const file_api_proto_rawDesc = "" +
	"\n" +
	"\tapi.proto\x12\agrpcapi\"G\n" +
	"\vItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05count\x18\x03 \x01(\rR\x05count\"I\n" +
	"\fItemResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x1d\n" +
	"\n" +
	"reserve_id\x18\x02 \x01(\tR\treserveId\"5\n" +
	"\x14CancelReserveRequest\x12\x1d\n" +
	"\n" +
	"reserve_id\x18\x01 \x01(\tR\treserveId\"1\n" +
	"\x15CancelReserveResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"&\n" +
	"\x0eAddressRequest\x12\x14\n" +
	"\x05table\x18\x01 \x01(\x05R\x05table\"D\n" +
	"\x0fAddressResponse\x12\x14\n" +
	"\x05added\x18\x01 \x01(\bR\x05added\x12\x1b\n" +
	"\tmore_info\x18\x02 \x01(\tR\bmoreInfo\"2\n" +
	"\x15CancelDeliveryRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"2\n" +
	"\x16CancelDeliveryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x7f\n" +
	"\x16ConfirmatorInfoRequest\x128\n" +
	"\x18confirmation_employee_id\x18\x01 \x01(\tR\x16confirmationEmployeeId\x12+\n" +
	"\x11confirmation_type\x18\x02 \x03(\tR\x10confirmationType\"V\n" +
	"\x17ConfirmatorInfoResponse\x12\x12\n" +
	"\x04sent\x18\x01 \x01(\bR\x04sent\x12'\n" +
	"\x0fconfirmation_id\x18\x02 \x01(\tR\x0econfirmationId\"D\n" +
	"\x19CancelConfirmationRequest\x12'\n" +
	"\x0fconfirmation_id\x18\x01 \x01(\tR\x0econfirmationId\"6\n" +
	"\x1aCancelConfirmationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x95\x01\n" +
	"\aStorage\x12:\n" +
	"\vReserveItem\x12\x14.grpcapi.ItemRequest\x1a\x15.grpcapi.ItemResponse\x12N\n" +
	"\rCancelReserve\x12\x1d.grpcapi.CancelReserveRequest\x1a\x1e.grpcapi.CancelReserveResponse2\x9f\x01\n" +
	"\bDelivery\x12@\n" +
	"\vSendToQueue\x12\x17.grpcapi.AddressRequest\x1a\x18.grpcapi.AddressResponse\x12Q\n" +
	"\x0eCancelDelivery\x12\x1e.grpcapi.CancelDeliveryRequest\x1a\x1f.grpcapi.CancelDeliveryResponse2\xc4\x01\n" +
	"\fConfirmation\x12U\n" +
	"\x10SendConfirmation\x12\x1f.grpcapi.ConfirmatorInfoRequest\x1a .grpcapi.ConfirmatorInfoResponse\x12]\n" +
	"\x12CancelConfirmation\x12\".grpcapi.CancelConfirmationRequest\x1a#.grpcapi.CancelConfirmationResponse2\x0e\n" +
	"\fNotificationB+Z)github.com/Krunis/manager-o-order/grpcapib\x06proto3"

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData []byte
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)))
	})
	return file_api_proto_rawDescData
}

var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_proto_goTypes = []any{
	(*ItemRequest)(nil),                // 0: grpcapi.ItemRequest
	(*ItemResponse)(nil),               // 1: grpcapi.ItemResponse
	(*CancelReserveRequest)(nil),       // 2: grpcapi.CancelReserveRequest
	(*CancelReserveResponse)(nil),      // 3: grpcapi.CancelReserveResponse
	(*AddressRequest)(nil),             // 4: grpcapi.AddressRequest
	(*AddressResponse)(nil),            // 5: grpcapi.AddressResponse
	(*CancelDeliveryRequest)(nil),      // 6: grpcapi.CancelDeliveryRequest
	(*CancelDeliveryResponse)(nil),     // 7: grpcapi.CancelDeliveryResponse
	(*ConfirmatorInfoRequest)(nil),     // 8: grpcapi.ConfirmatorInfoRequest
	(*ConfirmatorInfoResponse)(nil),    // 9: grpcapi.ConfirmatorInfoResponse
	(*CancelConfirmationRequest)(nil),  // 10: grpcapi.CancelConfirmationRequest
	(*CancelConfirmationResponse)(nil), // 11: grpcapi.CancelConfirmationResponse
}
var file_api_proto_depIdxs = []int32{
	0,  // 0: grpcapi.Storage.ReserveItem:input_type -> grpcapi.ItemRequest
	2,  // 1: grpcapi.Storage.CancelReserve:input_type -> grpcapi.CancelReserveRequest
	4,  // 2: grpcapi.Delivery.SendToQueue:input_type -> grpcapi.AddressRequest
	6,  // 3: grpcapi.Delivery.CancelDelivery:input_type -> grpcapi.CancelDeliveryRequest
	8,  // 4: grpcapi.Confirmation.SendConfirmation:input_type -> grpcapi.ConfirmatorInfoRequest
	10, // 5: grpcapi.Confirmation.CancelConfirmation:input_type -> grpcapi.CancelConfirmationRequest
	1,  // 6: grpcapi.Storage.ReserveItem:output_type -> grpcapi.ItemResponse
	3,  // 7: grpcapi.Storage.CancelReserve:output_type -> grpcapi.CancelReserveResponse
	5,  // 8: grpcapi.Delivery.SendToQueue:output_type -> grpcapi.AddressResponse
	7,  // 9: grpcapi.Delivery.CancelDelivery:output_type -> grpcapi.CancelDeliveryResponse
	9,  // 10: grpcapi.Confirmation.SendConfirmation:output_type -> grpcapi.ConfirmatorInfoResponse
	11, // 11: grpcapi.Confirmation.CancelConfirmation:output_type -> grpcapi.CancelConfirmationResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
