// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api.proto

package grpcapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Count         uint32                 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemRequest) Reset() {
	*x = ItemRequest{}
	mi := &file_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemRequest) ProtoMessage() {}

func (x *ItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemRequest.ProtoReflect.Descriptor instead.
func (*ItemRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

func (x *ItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ItemRequest) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	MoreInfo      string                 `protobuf:"bytes,2,opt,name=more_info,json=moreInfo,proto3" json:"more_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemResponse) Reset() {
	*x = ItemResponse{}
	mi := &file_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemResponse) ProtoMessage() {}

func (x *ItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemResponse.ProtoReflect.Descriptor instead.
func (*ItemResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *ItemResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ItemResponse) GetMoreInfo() string {
	if x != nil {
		return x.MoreInfo
	}
	return ""
}

type AddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         int32                  `protobuf:"varint,1,opt,name=table,proto3" json:"table,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressRequest) Reset() {
	*x = AddressRequest{}
	mi := &file_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressRequest) ProtoMessage() {}

func (x *AddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressRequest.ProtoReflect.Descriptor instead.
func (*AddressRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

func (x *AddressRequest) GetTable() int32 {
	if x != nil {
		return x.Table
	}
	return 0
}

type AddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Added         bool                   `protobuf:"varint,1,opt,name=added,proto3" json:"added,omitempty"`
	MoreInfo      string                 `protobuf:"bytes,2,opt,name=more_info,json=moreInfo,proto3" json:"more_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressResponse) Reset() {
	*x = AddressResponse{}
	mi := &file_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressResponse) ProtoMessage() {}

func (x *AddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressResponse.ProtoReflect.Descriptor instead.
func (*AddressResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3}
}

func (x *AddressResponse) GetAdded() bool {
	if x != nil {
		return x.Added
	}
	return false
}

func (x *AddressResponse) GetMoreInfo() string {
	if x != nil {
		return x.MoreInfo
	}
	return ""
}

type ConfirmatorInfoRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ConfirmationEmployeeId string                 `protobuf:"bytes,1,opt,name=confirmation_employee_id,json=confirmationEmployeeId,proto3" json:"confirmation_employee_id,omitempty"`
	ConfirmationType       []string               `protobuf:"bytes,2,rep,name=confirmation_type,json=confirmationType,proto3" json:"confirmation_type,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ConfirmatorInfoRequest) Reset() {
	*x = ConfirmatorInfoRequest{}
	mi := &file_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmatorInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmatorInfoRequest) ProtoMessage() {}

func (x *ConfirmatorInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmatorInfoRequest.ProtoReflect.Descriptor instead.
func (*ConfirmatorInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{4}
}

func (x *ConfirmatorInfoRequest) GetConfirmationEmployeeId() string {
	if x != nil {
		return x.ConfirmationEmployeeId
	}
	return ""
}

func (x *ConfirmatorInfoRequest) GetConfirmationType() []string {
	if x != nil {
		return x.ConfirmationType
	}
	return nil
}

type ConfirmatorInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sent          bool                   `protobuf:"varint,1,opt,name=sent,proto3" json:"sent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmatorInfoResponse) Reset() {
	*x = ConfirmatorInfoResponse{}
	mi := &file_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmatorInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmatorInfoResponse) ProtoMessage() {}

func (x *ConfirmatorInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmatorInfoResponse.ProtoReflect.Descriptor instead.
func (*ConfirmatorInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{5}
}

func (x *ConfirmatorInfoResponse) GetSent() bool {
	if x != nil {
		return x.Sent
	}
	return false
}

var File_api_proto protoreflect.FileDescriptor

const file_api_proto_rawDesc = "" +
	"\n" +
	"\tapi.proto\x12\agrpcapi\"G\n" +
	"\vItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05count\x18\x03 \x01(\rR\x05count\"G\n" +
	"\fItemResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x1b\n" +
	"\tmore_info\x18\x02 \x01(\tR\bmoreInfo\"&\n" +
	"\x0eAddressRequest\x12\x14\n" +
	"\x05table\x18\x01 \x01(\x05R\x05table\"D\n" +
	"\x0fAddressResponse\x12\x14\n" +
	"\x05added\x18\x01 \x01(\bR\x05added\x12\x1b\n" +
	"\tmore_info\x18\x02 \x01(\tR\bmoreInfo\"\x7f\n" +
	"\x16ConfirmatorInfoRequest\x128\n" +
	"\x18confirmation_employee_id\x18\x01 \x01(\tR\x16confirmationEmployeeId\x12+\n" +
	"\x11confirmation_type\x18\x02 \x03(\tR\x10confirmationType\"-\n" +
	"\x17ConfirmatorInfoResponse\x12\x12\n" +
	"\x04sent\x18\x01 \x01(\bR\x04sent2A\n" +
	"\aStorage\x126\n" +
	"\aGetItem\x12\x14.grpcapi.ItemRequest\x1a\x15.grpcapi.ItemResponse2L\n" +
	"\bDelivery\x12@\n" +
	"\vSendToQueue\x12\x17.grpcapi.AddressRequest\x1a\x18.grpcapi.AddressResponse2e\n" +
	"\fConfirmation\x12U\n" +
	"\x10SendConfirmation\x12\x1f.grpcapi.ConfirmatorInfoRequest\x1a .grpcapi.ConfirmatorInfoResponse2\x0e\n" +
	"\fNotificationB+Z)github.com/Krunis/manager-o-order/grpcapib\x06proto3"

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData []byte
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)))
	})
	return file_api_proto_rawDescData
}

var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_goTypes = []any{
	(*ItemRequest)(nil),             // 0: grpcapi.ItemRequest
	(*ItemResponse)(nil),            // 1: grpcapi.ItemResponse
	(*AddressRequest)(nil),          // 2: grpcapi.AddressRequest
	(*AddressResponse)(nil),         // 3: grpcapi.AddressResponse
	(*ConfirmatorInfoRequest)(nil),  // 4: grpcapi.ConfirmatorInfoRequest
	(*ConfirmatorInfoResponse)(nil), // 5: grpcapi.ConfirmatorInfoResponse
}
var file_api_proto_depIdxs = []int32{
	0, // 0: grpcapi.Storage.GetItem:input_type -> grpcapi.ItemRequest
	2, // 1: grpcapi.Delivery.SendToQueue:input_type -> grpcapi.AddressRequest
	4, // 2: grpcapi.Confirmation.SendConfirmation:input_type -> grpcapi.ConfirmatorInfoRequest
	1, // 3: grpcapi.Storage.GetItem:output_type -> grpcapi.ItemResponse
	3, // 4: grpcapi.Delivery.SendToQueue:output_type -> grpcapi.AddressResponse
	5, // 5: grpcapi.Confirmation.SendConfirmation:output_type -> grpcapi.ConfirmatorInfoResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
